### ISSUE TITLE
Error: Process completed with exit code 1

### ISSUE THREAD

**Issue by ghost** [timovv/notion-website-template#1]
Hi. Thanks for your work! Do you plan to fix "Error: Process completed with exit code 1" that occure after  run the action "Publish Notion website to GitHub Pages"?

**Comment by timovv** [comment]
Hi, thanks for the report and my apologies for the delayed response. I haven't had much time to look at this project recently. Do you happen to have more information -- logs from the failure or anything -- since that would definitely help me figure it out.

The build is definitely failing on this repo, but that's because the Notion website URL is left as a placeholder.

**Comment by timovv** [comment]
(hopefully) resolved by #3.
