### ISSUE TITLE
Build Loconotion docker image failed.

### ISSUE THREAD

**Issue by bbinarygo** [timovv/notion-website-template#14]
Hi @timovv , idk why just do like your format but encounter this problem:
```
ERROR: failed to solve: process "/bin/sh -c wget --no-verbose -O /tmp/chrome.deb [https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb](https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_$%7BCHROME_VERSION%7D_amd64.deb)   && apt install -y /tmp/chrome.deb   && rm /tmp/chrome.deb" did not complete successfully: exit code: 8
Service 'loconotion' failed to build : Build failed
Error: Process completed with exit code 1.
```

**Comment by tkasarla** [comment]
@timovv @ngbao161199 I have the same error right now.

**Comment by estatements** [comment]
same here

**Comment by andrewgetzdata** [comment]
@timovv -- Same here, this is a great concept! Would love to use it if I could. 

Happy to donate to a developer fund to get it fixed! 💸

**Comment by andrewgetzdata** [comment]
@timovv -- Found a solution in the Loconotion Repo that worked for me. 

https://github.com/leoncvlt/loconotion/issues/137#issuecomment-1712693550

![Screenshot 2023-09-10 at 6 29 12 PM](https://github.com/timovv/notion-website-template/assets/20614809/95fb5e8a-0304-4f47-af45-36047e9ea124)

CC: @estatements @tkasarla @ngbao161199

**Comment by timovv** [comment]
Hi folks, thanks for bringing this to my attention. I think the best course of action here is to drop Docker entirely and just install the chromedriver directly onto the runner. That will bypass this issue since we'll just be installing the web driver from the Ubuntu repository, which should keep things up-to-date enough.

Using the Docker image has caused some other weirdness in the past, so I am hoping that getting rid of it will streamline things in other areas too.

Fix incoming!

**Comment by timovv** [comment]
I have merged the change to remove the dependency on Docker. It works for me when I test. Give it a try and let me know if it's working for you all.
